### PR TITLE
11 implement csrf token

### LINKED ISSUE #11: Implement CSRF
Implement CSRF for forms, This needs to be implemented as a middleware properly.

You can review CSRF technical details here : https://www.synopsys.com/glossary/what-is-csrf.html

### PR DESCRIPTION
**Pull request by eclipsed-ninja**
Closes #11 

CSRF is implemented where at each request there would be a csrf token sent to the template which is verified when there is a POST request. An example has been setup at authentication login.html

Similar setup will be needed for any forms else will raise a CSRF error

### CODE REVIEW

**Review by RajP7Jowa — APPROVED** [review]
can we store auth token on this cache or manage with full JSON.string(LOGIN USER row) ?

**Review by RajP7Jowa — CHANGES_REQUESTED** [review]
missing documentation

**Comment by eclipsed-ninja** [comment]
> missing documentation of how to manage records with this cache like use multi key on csrf or store json string with key-value

Not sure I understand what's needed here, CSRF is nothing but a simple check that forms are being filled out live and not injected through POST as CSRF will change from request to request. There is nothing needed except adding a go template variable like show in authentication/login and that's it. There's no other changes needed in code.

**Review by RajP7Jowa — APPROVED** [review]

**Review by RajP7Jowa — APPROVED** [review]
here csrf use on Form, and pending for ajax, curl, api calling right ?

**Comment by eclipsed-ninja** [comment]
I'm adding the example for ajax as well so it's clear for you :)

**Comment by eclipsed-ninja** [comment]
I've added a switch to disable CSRF when we're in microservice mode, for ajax query we just need to set header which can be picked up from gotemplate variable

**Review by GuitarGeekCoder — APPROVED** [review]

**Pull request merged**
